import {assert} from '@augment-vir/assert';
import {describe, it, itCases} from '@augment-vir/test';
import {userLocale} from '../locale.js';
import {getMonthNames, MonthName} from './month.js';

describe(getMonthNames.name, () => {
    it("uses the user's locale", () => {
        assert.deepEquals(
            getMonthNames(),
            getMonthNames({
                locale: userLocale,
            }),
        );
    });

    itCases(getMonthNames, [
        {
            it: 'gets English names',
            input: {
                locale: 'en',
            },
            expect: {
                long: {
                    numbered: {
                        '1': 'January',
                        '2': 'February',
                        '3': 'March',
                        '4': 'April',
                        '5': 'May',
                        '6': 'June',
                        '7': 'July',
                        '8': 'August',
                        '9': 'September',
                        '10': 'October',
                        '11': 'November',
                        '12': 'December',
                    },
                    keyed: {
                        [MonthName.January]: 'January',
                        [MonthName.February]: 'February',
                        [MonthName.March]: 'March',
                        [MonthName.April]: 'April',
                        [MonthName.May]: 'May',
                        [MonthName.June]: 'June',
                        [MonthName.July]: 'July',
                        [MonthName.August]: 'August',
                        [MonthName.September]: 'September',
                        [MonthName.October]: 'October',
                        [MonthName.November]: 'November',
                        [MonthName.December]: 'December',
                    },
                    indexed: {
                        '0': 'January',
                        '1': 'February',
                        '2': 'March',
                        '3': 'April',
                        '4': 'May',
                        '5': 'June',
                        '6': 'July',
                        '7': 'August',
                        '8': 'September',
                        '9': 'October',
                        '10': 'November',
                        '11': 'December',
                    },
                },
                short: {
                    numbered: {
                        '1': 'Jan',
                        '2': 'Feb',
                        '3': 'Mar',
                        '4': 'Apr',
                        '5': 'May',
                        '6': 'Jun',
                        '7': 'Jul',
                        '8': 'Aug',
                        '9': 'Sep',
                        '10': 'Oct',
                        '11': 'Nov',
                        '12': 'Dec',
                    },
                    keyed: {
                        [MonthName.January]: 'Jan',
                        [MonthName.February]: 'Feb',
                        [MonthName.March]: 'Mar',
                        [MonthName.April]: 'Apr',
                        [MonthName.May]: 'May',
                        [MonthName.June]: 'Jun',
                        [MonthName.July]: 'Jul',
                        [MonthName.August]: 'Aug',
                        [MonthName.September]: 'Sep',
                        [MonthName.October]: 'Oct',
                        [MonthName.November]: 'Nov',
                        [MonthName.December]: 'Dec',
                    },
                    indexed: {
                        '0': 'Jan',
                        '1': 'Feb',
                        '2': 'Mar',
                        '3': 'Apr',
                        '4': 'May',
                        '5': 'Jun',
                        '6': 'Jul',
                        '7': 'Aug',
                        '8': 'Sep',
                        '9': 'Oct',
                        '10': 'Nov',
                        '11': 'Dec',
                    },
                },
                narrow: {
                    numbered: {
                        '1': 'J',
                        '2': 'F',
                        '3': 'M',
                        '4': 'A',
                        '5': 'M',
                        '6': 'J',
                        '7': 'J',
                        '8': 'A',
                        '9': 'S',
                        '10': 'O',
                        '11': 'N',
                        '12': 'D',
                    },
                    keyed: {
                        [MonthName.January]: 'J',
                        [MonthName.February]: 'F',
                        [MonthName.March]: 'M',
                        [MonthName.April]: 'A',
                        [MonthName.May]: 'M',
                        [MonthName.June]: 'J',
                        [MonthName.July]: 'J',
                        [MonthName.August]: 'A',
                        [MonthName.September]: 'S',
                        [MonthName.October]: 'O',
                        [MonthName.November]: 'N',
                        [MonthName.December]: 'D',
                    },
                    indexed: {
                        '0': 'J',
                        '1': 'F',
                        '2': 'M',
                        '3': 'A',
                        '4': 'M',
                        '5': 'J',
                        '6': 'J',
                        '7': 'A',
                        '8': 'S',
                        '9': 'O',
                        '10': 'N',
                        '11': 'D',
                    },
                },
            },
        },
        {
            it: 'gets Spanish names',
            input: {
                locale: 'es',
            },
            // cspell:disable
            expect: {
                long: {
                    numbered: {
                        '1': 'enero',
                        '2': 'febrero',
                        '3': 'marzo',
                        '4': 'abril',
                        '5': 'mayo',
                        '6': 'junio',
                        '7': 'julio',
                        '8': 'agosto',
                        '9': 'septiembre',
                        '10': 'octubre',
                        '11': 'noviembre',
                        '12': 'diciembre',
                    },
                    keyed: {
                        [MonthName.January]: 'enero',
                        [MonthName.February]: 'febrero',
                        [MonthName.March]: 'marzo',
                        [MonthName.April]: 'abril',
                        [MonthName.May]: 'mayo',
                        [MonthName.June]: 'junio',
                        [MonthName.July]: 'julio',
                        [MonthName.August]: 'agosto',
                        [MonthName.September]: 'septiembre',
                        [MonthName.October]: 'octubre',
                        [MonthName.November]: 'noviembre',
                        [MonthName.December]: 'diciembre',
                    },
                    indexed: {
                        '0': 'enero',
                        '1': 'febrero',
                        '2': 'marzo',
                        '3': 'abril',
                        '4': 'mayo',
                        '5': 'junio',
                        '6': 'julio',
                        '7': 'agosto',
                        '8': 'septiembre',
                        '9': 'octubre',
                        '10': 'noviembre',
                        '11': 'diciembre',
                    },
                },
                short: {
                    numbered: {
                        '1': 'ene',
                        '2': 'feb',
                        '3': 'mar',
                        '4': 'abr',
                        '5': 'may',
                        '6': 'jun',
                        '7': 'jul',
                        '8': 'ago',
                        '9': 'sept',
                        '10': 'oct',
                        '11': 'nov',
                        '12': 'dic',
                    },
                    keyed: {
                        [MonthName.January]: 'ene',
                        [MonthName.February]: 'feb',
                        [MonthName.March]: 'mar',
                        [MonthName.April]: 'abr',
                        [MonthName.May]: 'may',
                        [MonthName.June]: 'jun',
                        [MonthName.July]: 'jul',
                        [MonthName.August]: 'ago',
                        [MonthName.September]: 'sept',
                        [MonthName.October]: 'oct',
                        [MonthName.November]: 'nov',
                        [MonthName.December]: 'dic',
                    },
                    indexed: {
                        '0': 'ene',
                        '1': 'feb',
                        '2': 'mar',
                        '3': 'abr',
                        '4': 'may',
                        '5': 'jun',
                        '6': 'jul',
                        '7': 'ago',
                        '8': 'sept',
                        '9': 'oct',
                        '10': 'nov',
                        '11': 'dic',
                    },
                },
                narrow: {
                    numbered: {
                        '1': 'E',
                        '2': 'F',
                        '3': 'M',
                        '4': 'A',
                        '5': 'M',
                        '6': 'J',
                        '7': 'J',
                        '8': 'A',
                        '9': 'S',
                        '10': 'O',
                        '11': 'N',
                        '12': 'D',
                    },
                    keyed: {
                        [MonthName.January]: 'E',
                        [MonthName.February]: 'F',
                        [MonthName.March]: 'M',
                        [MonthName.April]: 'A',
                        [MonthName.May]: 'M',
                        [MonthName.June]: 'J',
                        [MonthName.July]: 'J',
                        [MonthName.August]: 'A',
                        [MonthName.September]: 'S',
                        [MonthName.October]: 'O',
                        [MonthName.November]: 'N',
                        [MonthName.December]: 'D',
                    },
                    indexed: {
                        '0': 'E',
                        '1': 'F',
                        '2': 'M',
                        '3': 'A',
                        '4': 'M',
                        '5': 'J',
                        '6': 'J',
                        '7': 'A',
                        '8': 'S',
                        '9': 'O',
                        '10': 'N',
                        '11': 'D',
                    },
                },
            },
        },
    ]);
});
